-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 7c003425b35fff516c0ee88f4040c8c208d474bd
    hooks:
    -   id: flake8
    -   id: trailing-whitespace
    -   id: name-tests-test
-   repo: git@github.com:pre-commit/scss-lint
    sha: 75111a8769605839c3aee3eabbbbfa529bdb0358
    hooks:
    -   id: scss-lint
-   repo: git@github.com:pre-commit/pre-commit
    sha: 7edb438d76b7b977b7b8a6b16422af7b8d8c13cd
    hooks:
    -   id: validate_config
-   repo: git@github.com:pre-commit/ruby-lint
    sha: 11522d47a7ee3a382d819e009ebcd976f6541c76
    hooks:
    -   id: ruby-lint
