-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: f69737ee198a488f4c0478e7ab95333883f6a2d9
    hooks:
    -   id: flake8
    -   id: trailing-whitespace
    -   id: name-tests-test
-   repo: git://github.com/pre-commit/mirrors-scss-lint
    sha: d7266131da322d6d76a18d6a3659f21025d9ea11
    hooks:
    -   id: scss-lint
-   repo: git@github.com:pre-commit/pre-commit
    sha: 16b3a370475e8f91e1ea57d4680842cdd9bdfaf6
    hooks:
    -   id: validate_config
-   repo: git://github.com/pre-commit/mirrors-ruby-lint
    sha: f4b537e0bf868fc6baefcb61288a12b35aac2157
    hooks:
    -   id: ruby-lint
-   repo: git://github.com/pre-commit/mirrors-jshint
    sha: 8e7fa9caad6f7b2aae8d2c7b64f457611416192b
    hooks:
    -   id: jshint
